name: Auto Merge
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge:
    uses: RokctAI/shared-workflows/.github/workflows/universal-merge.yml@main
    permissions:
      pull-requests: write
      contents: write
    with:
      allowed_users: 'RendaniSinyage, RendaniSinyage, rokctbot, rokctbot[bot]'
    secrets: inherit
