name: ToDo Bot
on:
  push:
    branches: [main]

jobs:
  todo:
    uses: RokctAI/shared-workflows/.github/workflows/universal-todo.yml@main
    permissions:
      contents: read
      issues: write
    secrets: inherit
